# Generated by Django 3.2.3 on 2021-05-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MutualFundsScheme',
            new_name='MutualFundsCode',
        ),
    ]
